// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yihztkqrfxgvvsovpmfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaHp0a3FyZnhndnZzb3ZwbWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODMwMjAsImV4cCI6MjA3MTU1OTAyMH0.QmqeyNIULbMxwC2jniJXgG2-uPfvBp6Z_MiT7MQLN3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});